//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Getraenkemarkt
{
    using System;
    using System.Collections.Generic;
    
    public partial class beverage
    {
        public int beverage_ID { get; set; }
        public string beverageName { get; set; }
        public int beverageQuantity { get; set; }
    }
}
